""GVIM RC

"""""""""""""""""""" GLOBAL
set lines=56
set columns=210

"""disable blicking/flashing
set vb t_vb= 
"""""""""""""""""""" CUSTOM FUNCTIONS

" nnoremap <C-X><C-S> i<C-X><C-S>

"""Font

if has('gui_running')
  set guifont=PragmataPro\ 8
endif
