#PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

#Options
zstyle ':completion:*' menu select
setopt histignorealldups sharehistory

HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

autoload -U colors && colors
autoload -U compinit

compinit

bindkey -v
# export EDITOR="vim"
export EDITOR="gvim"

#Alias

alias prompt='$HOME/Apps/infos.sh'

#Theme

PROMPT="%{$fg[red]%}% %M %{$reset_color%}% %{$fg[cyan]%}% %~ %{$reset_color%}%"
